name: Generate Pac-Man Contribution Graph

on:
  schedule:
    # Run every 24 hours
    - cron: "0 */24 * * *"

  # Allow manual execution
  workflow_dispatch:

  # Regenerate when the profile repository changes
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: GeorgeLxL
          games: "pacman"

      - name: Publish generated SVG
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}